"""
Detection rule generation (Sigma / YARA) from a saved investigation.

Rules are generated deterministically from the investigation's structured
data (verdict, severity, IOCs, MITRE technique) — no LLM involved, so two
exports of the same investigation are byte-identical. Stable rule IDs are
derived from the investigation id + artifact hash so re-exporting the same
case keeps the same rule id.
"""

import datetime
import hashlib
import uuid


def stable_uuid(seed) -> str:
    """Derive a deterministic UUID v5-style string from an arbitrary seed."""
    digest = hashlib.sha256(str(seed).encode("utf-8")).digest()
    return str(uuid.UUID(bytes=digest[:16]))


def _level_for(severity: str) -> str:
    return {"critical": "critical", "high": "high", "medium": "medium"}.get(
        (severity or "").lower(), "low"
    )


def _mitre_url(row) -> str | None:
    mitre_id = row.get("mitre_id")
    return f"https://attack.mitre.org/techniques/{mitre_id}/" if mitre_id else None


def _clean_yara(value: str) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def generate_sigma_rule(row) -> str:
    """Build a Sigma YAML rule detecting the investigation's indicators."""
    iocs = row.get("iocs") or {}
    mitre_id = row.get("mitre_id")
    technique = f"{mitre_id} - {row.get('mitre_name', 'Unknown')}" if mitre_id else "Unknown"

    def _yaml_list(items):
        return "".join(f"            - '{str(v)}'\n" for v in items)

    detection = []
    ips = iocs.get("ips") or []
    domains = iocs.get("domains") or []
    urls = iocs.get("urls") or []
    hashes = iocs.get("hashes") or []

    if ips:
        detection.append("    selection_ip:\n        net.source.ip:\n" + _yaml_list(ips))
    if domains:
        detection.append("    selection_domain:\n        dns.query.name:\n" + _yaml_list(domains))
    if urls:
        detection.append("    selection_url:\n        http.request.url:\n" + _yaml_list(urls))
    if hashes:
        detection.append("    selection_hash:\n        file.sha256:\n" + _yaml_list(hashes))

    if detection:
        condition = "selection_ip or selection_domain or selection_url or selection_hash"
        detection_block = "\n".join(detection)
        # Trim the trailing condition to only the selections that exist.
        present = [s for s in ("selection_ip", "selection_domain", "selection_url", "selection_hash")
                   if f"    {s}:" in detection_block]
        condition = " or ".join(present)
    else:
        detection_block = "    selection_artifact:\n        process.executable:\n            - '*'"
        condition = "selection_artifact"

    refs = ["https://attack.mitre.org/techniques/"]
    ref_lines = "\n".join(f"    - {r}" for r in refs)
    mitre_url = _mitre_url(row)
    if mitre_url:
        ref_lines = f"    - {mitre_url}"

    tags = []
    if mitre_id:
        tags.append(f"attack.{mitre_id.lower()}")
    tag_lines = "".join(f"    - {t}\n" for t in tags)

    return f"""title: CyberGuru - Suspicious {row.get('verdict', 'activity')} via {technique}
id: {stable_uuid(f'sigma:{row.get('id')}:{row.get('artifact_hash')}')}
status: experimental
description: Detection rule generated by CyberGuru AI for investigation #{row.get('id')} ({row.get('verdict', 'inconclusive')} / {row.get('severity', 'low')}). Technique: {technique}.
references:
{ref_lines}
author: CyberGuru AI
date: {datetime.date.today().isoformat()}
logsource:
    category: process_creation
    product: windows
detection:
{detection_block}
    condition: {condition}
falsepositives:
    - Unknown
level: {_level_for(row.get('severity'))}
tags:
{tag_lines.rstrip()}
"""


def generate_yara_rule(row) -> str:
    """Build a YARA rule matching the investigation's raw indicator strings."""
    iocs = row.get("iocs") or {}
    mitre_url = _mitre_url(row)

    strings = []
    for label, key, opts in (
        ("ip", "ips", "ascii wide"),
        ("domain", "domains", "ascii wide nocase"),
        ("url", "urls", "ascii wide nocase"),
        ("hash", "hashes", "ascii"),
    ):
        for idx, value in enumerate(iocs.get(key) or [], start=1):
            strings.append(f'        ${label}_{idx} = "{_clean_yara(value)}" {opts}')

    if not strings:
        placeholder = f"CYBERGURU_INVESTIGATION_{row.get('id')}"
        strings = [f'        $placeholder = "{placeholder}"']

    string_block = "\n".join(strings)
    meta_lines = [
        '        author = "CyberGuru AI"',
        f'        date = "{datetime.date.today().isoformat()}"',
        f'        description = "Rule generated by CyberGuru AI for investigation #{row.get("id")} '
        f'({row.get("verdict", "inconclusive")} / {row.get("severity", "low")})"',
        f'        severity = "{_level_for(row.get("severity"))}"',
    ]
    if mitre_url:
        meta_lines.append(f'        reference = "{mitre_url}"')
    else:
        meta_lines.append('        reference = "https://attack.mitre.org/techniques/"')
    meta_block = "\n".join(meta_lines)

    return f"""rule CyberGuru_Investigation_{row.get('id')} {{
    meta:
{meta_block}
    strings:
{string_block}
    condition:
        any of them
}}
"""
